apiVersion: v1
kind: ReplicationController
metadata:  
 name: rc-example
spec:
 replicas: 4
 template: 
  metadata:
   name: web
   labels:
    run: test
  spec: 
   containers: 
   - name: c1
     image: quay.io/gauravkumar9130/mywebapp
     imagePullPolicy: IfNotPresent
